# Generated by Django 6.0.2 on 2026-03-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_perfil_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='genero',
            field=models.CharField(choices=[('NI', 'Prefiro não informar'), ('M', 'Masculino'), ('F', 'Feminino')], max_length=20, null=True),
        ),
    ]
