# Generated by Django 6.0.2 on 2026-03-14 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordemdeservico',
            options={'ordering': ['-data_de_criacao'], 'permissions': [('pode_visualizar_todas_os', 'Pode visualizar todas as ordens de serviço'), ('pode_atribuir_tecnico', 'Pode atribuir uma Ordem de Serviço a um técnico'), ('pode_fechar_os', 'Pode fechar uma ordem de serviçox')], 'verbose_name': 'Ordem de Serviço', 'verbose_name_plural': 'Ordens de Serviço'},
        ),
    ]
